title: Work Plan for Strengthening Capacities in the Management of WEAP
description: Training Workshop Content Page (Tumbes, Perú - 2024)
theme: just-the-docs
logo: "https://www.sei.org/wp-content/themes/sei/assets/src/sprite-images/logo.svg"

url: https://just-the-docs.github.io

aux_links:
  Template Repository: https://cafigueroao.github.io/peru-training-web-2024
  "SEI - Stockholm Environment Institute":
    - "//www.sei.org/centres/latinoamerica/"
