title: Just the Docs Template (title)
description: A starter template for a Jeykll site using the Just the Docs theme! (description)
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  Template Repository: https://cafigueroao.github.io/peru-training-web-2024
